### ISSUE TITLE
neo4j auth fail

### ISSUE THREAD

**Issue by psyc0** [yantisj/netgrph#1]
Followed the instructions per the inst-doc, seems when populating data I have problems with auth to neo4j

<pre>
./test/first_import.sh 
2017-01-20 10:56:47,028 nglib:INFO: Enabled STDOUT Logging
Traceback (most recent call last):
  File "./ngupdate.py", line 140, in <module>
    nglib.init_nglib(config_file)
  File "/home/peterjoh/netgrph/nglib/__init__.py", line 200, in init_nglib
    bolt_ses = get_db_client(dbhost, dbuser, dbpass, bolt=True)
  File "/home/peterjoh/netgrph/nglib/__init__.py", line 86, in get_db_client
    auth_token = basic_auth(dbuser, dbpass)
NameError: name 'basic_auth' is not defined
</pre>

the think i reacted upon was that neo4j has changed some parameters in neo4j.conf

`dbms.connectors.default_listen_address=0.0.0.0`
`dbms.connector.http.listen_address=0.0.0.0:7474`

instead of the suggested `dbms.connector.http.address=0.0.0.0:7474`

I can login to neo4j and the credentials work there, havent gotten around to check the code where basic_auth is defined

**Comment by psyc0** [comment]
after some digging around this is not provided in neo4j 
from neo4j.v1.exceptions import CypherError, ProtocolError
going further without them lands me in 
`neo4j.bolt.connection.ServiceUnavailable: Failed to write to closed connection Address(host='127.0.0.1', port=7687)` even though i see the port being open

**Comment by yantisj** [comment]
Hey, is this neo4j 3.1? I'm still on 3.0.7 on my install, which may contribute to this. I'm going to assume something changed either with the bolt driver or the latest version of the database. I'll kick off a fresh install today and see if I run into the same problem.

**Comment by yantisj** [comment]
Hey, I was able to reproduce the problem and should have a fix today, stay tuned.

Thanks

**Comment by yantisj** [comment]
Try switching to the dev branch 'git checkout dev', doing another pip install -r requirements.txt and test it one more time. The new neo4j driver made some changes and I need to test them, so in the meantime, I pinned the version to 1.0.2 int requirements.txt instead of the new 1.1.0 version.

If that works for you, I will push it to master for now and then work on testing with the new driver.

Jonathan

**Comment by psyc0** [comment]
Alright will try the dev branch, I used jessie first, now running on trusty, I checked out 3.0.7 neo4j also.

**Comment by psyc0** [comment]
it worked with the dev branch in trusty and neo4j 3.0.7.
/Peter

**Comment by yantisj** [comment]
Great, they changed some things with the new neo4j native driver which broke compatibility. I’ll make sure to pin these going forward until they’re tested. Neo4j 3.1 also works just fine, it was simply the driver issue.

Jonathan

**Comment by psyc0** [comment]
Thanks Jonathan, 
I used this lib as part of a hackday project but I will move on to try populating it with my actual data (as i stumbled upon these errors I did not have the time before presentations :)) 
will try to keep my efforts going in trying this out, think I might have a lldp crawler that might be handy in the plotting.
on a complete side-note, would geo-location be something you might populate from the nodes to get neo/d3 to render a "geo-correct" image instead of the starting blob :) 
thanks for your help

**Comment by yantisj** [comment]
Hey no problem, thats very cool. Sorry about not pinning the versions, I should have done this earlier. I’m going to be dockerizing this app before-long to make it easier to deploy and support.

Geo-location is a great idea, and from what I understand, Neo4j works very well with it. This is something we could easily add. Eventually, I plan to allow arbitrary extended attributes to be added via the API, but I’ve been pulled onto another project at the moment. Regardless, we use this application extensively internally and within a month or so, I will be back working on getting it containerized and adding a bunch of API updates.

If you would, open an issue on the geo-location describing what you need and we’ll get it added.

Jonathan

**Comment by psyc0** [comment]
Docker would be nice :+1: 
closing since version is pinned in master now (also created new issue on geolocation.)
