### ISSUE TITLE
Is Netgrph discoverying the network topology ?

### ISSUE THREAD

**Issue by ikus060** [yantisj/netgrph#3]
Hello,

I've start reading the doc about Netgrph and it's unclear if netgraph is actually discoverying the network topology. Here our usecase.

We are managing multiple disconnected customer network. We have relatively no knowledge about the network topology of these customer network. Most equipment network equipment are Cisco router and switch. We do have SNMP read access to the devices.

We want to discover the topology of these network: what is connected to what. We would like to include router, switch, but also other component part of the network like servers, printers, etc.

Is Netgrph matches our usecase ? If not do you know another tool capable of doing such discovery ?

**Comment by yantisj** [comment]
Hey Patrik,

Unfortunately NetGrph just processes topology data from other discovery tools, so I doubt it will work for you here. If you do not have ssh access, only SNMP, you would need to use some SNMP walk tool to find all of your devices.

I would check out this tool:

https://github.com/ytti/netcrawl <https://github.com/ytti/netcrawl>

There’s a few out there but it’s one of the better ones. There’s also Netdisco which is totally SNMP based from what I understand.

Best,
Jonathan

**Comment by yantisj** [comment]
Hey, I ended up writing a tool for this. Probably too late, but this will discover a Cisco topology for you as well as output a devicelist of all discovered devices (CDP or LLDP): https://github.com/yantisj/ndcrawl
